language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  # - jruby-19mode
  # - rbx-19mode

gemfile:
  - ci/Gemfile.rails-4.0.x

env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
script: bundle exec rake specs_with_db_ixes

before_script:
  - mysql -e 'create database closure_tree_test'
  - psql -c 'create database closure_tree_test' -U postgres
