language: ruby
rvm:
  - 1.8.7
  - 1.9.3
# TODO: - jruby-18mode # JRuby in 1.8 mode
# TODO: - jruby-19mode # JRuby in 1.9 mode
# TODO: - rbx-18mode

gemfile:
# TODO: - ci/Gemfile.rails-2.3.x
  - ci/Gemfile.rails-3.0.x
  - ci/Gemfile.rails-3.1.x
  - ci/Gemfile.rails-3.2.x
env:
  - DB=sqlite3
  - DB=mysql
  - DB=postgresql
script: bundle exec rake
