title: Closure tree
description: Easily and efficiently make your ActiveRecord model support hierarchies
google_analytics: UA-38750440-1
show_downloads: true
theme: jekyll-theme-leap-day

gems:
  - jekyll-mentions
