sqlite3:
  adapter: <%= "jdbc" if defined? JRUBY_VERSION %>sqlite3
  database: closure_tree.sqlite3.db
  pool: 50

sqlite3mem:
  adapter: <%= "jdbc" if defined? JRUBY_VERSION %>sqlite3
  database: ":memory:"
  pool: 50

pg:
  adapter: postgresql
  username: postgres
  database: closure_tree_test
  min_messages: ERROR
  pool: 50

mysql:
  adapter: mysql2
  host: localhost
  username: root
  database: closure_tree_test
  pool: 50
