sqlite3:
  adapter: sqlite3
  database: closure_tree.sqlite3.db
sqlite3mem:
  adapter: sqlite3
  database: ":memory:"
postgresql:
  adapter: postgresql
  username: postgres
  password: postgres
  database: closure_tree_plugin_test
  min_messages: ERROR
mysql:
  adapter: mysql
  host: localhost
  username: root
  password:
  database: closure_tree_plugin_test
